### PR TITLE
Automatic launch on Windows

### PR DESCRIPTION
**Pull request by ghost**
Hi! Hi! 

Nice project! I tried to run it on Windows 10 but I was fooled by the fact that the server was not running:/
I don't know if you were planning on doing things in the future, but for now, I've done a little script to run all this automatically on Windows, because I'm a slacker. 
Don't hesitate to refuse the PR if you had already planned something else ^^

I will try to do the code for Linux/MacOS later today, when my VM is ready

### CODE REVIEW

**Comment by ShiroUsagi-san** [comment]
HI,
I'm pretty sure that launching both client and server at the same time is a bad practice, because you don't want this behavior in production (you'll never be running server and client on the same computer).
So I'm not sure that this PR is really needed

**Comment by Vahelnir** [comment]
I don't think it is a bad practice. In many games, when you start a solo game, you are in fact playing on a local server.
(minecraft, csgo...)

**Comment by ghost** [comment]
This is what I also think but indeed if the game has a global server and it is destined to be hosted on a linux server, this pr is indeed not too useful :p

**Comment by ShiroUsagi-san** [comment]
Yes, maybe but it's not by launching a script like that...
But, sure, playing lan games could be super fun. I'm not 100% sure that is the best way to do.
We should maybe handle this in the code, to increase user experience, feel free to help :)

**Comment by ghost** [comment]
I agree, I close the PR and I will see to launch the code directly from the client at startup time

**Comment by hugolgst** [comment]
Vous savez vous pouvez parler français, le projet est en français sur GitHub

**Pull request closed without merging**
